import sys

sys.path.append("../../")

from .base import *

from scaut.elegant import eleget, eleput

# GENERAL
NOISE_LEVEL = 0.5

VERIFY_MOTOR = True

DELAY = milli

TOLERANCE = 0.1

MAX_TRIES = 3

SAMPLE_SIZE = 10

SAVE_SCAN = True

DIRNAME_DATA = "data/dev"

SAVE_ORIGINAL_MOTOR_VALUES = True

PARALLEL = False

REPEAT = 1

GET_FUNC = eleget

PUT_FUNC = eleput

# ERRORS
ELEMENT_X_POSITION_ERROR = milli

ELEMENT_Y_POSITION_ERROR = milli

ELEMENT_Z_POSITION_ERROR = milli

ELEMENT_ROTATION_ERROR = milli

ELEMENT_FIELD_ERROR = milli

# MOTORS
DEFAULT_MOTOR_VALUES = [0]

DEFAULT_DELTA_KICK = 0.1

HORIZONTAL_CORRECTORS = [  
    ["MG-LA1.CL1.HKICK", DEFAULT_MOTOR_VALUES],
    ["MG-LA1.CL2.HKICK", DEFAULT_MOTOR_VALUES],
    ["MG-LA2.CL3.HKICK", DEFAULT_MOTOR_VALUES],
    ["MG-LA3.CL4.HKICK", DEFAULT_MOTOR_VALUES],
    ["MG-LA4.CL5.HKICK", DEFAULT_MOTOR_VALUES],
    ["MG-LA5.CL6.HKICK", DEFAULT_MOTOR_VALUES],
]

VERTICAL_CORRECTORS = [  
    ["MG-LA1.CL1.VKICK", DEFAULT_MOTOR_VALUES],
    ["MG-LA1.CL2.VKICK", DEFAULT_MOTOR_VALUES],
    ["MG-LA2.CL3.VKICK", DEFAULT_MOTOR_VALUES],
    ["MG-LA3.CL4.VKICK", DEFAULT_MOTOR_VALUES],
    ["MG-LA4.CL5.VKICK", DEFAULT_MOTOR_VALUES],
    ["MG-LA5.CL6.VKICK", DEFAULT_MOTOR_VALUES],
]

QUADS = [
    ["MG-LA1.QLF1.K1", DEFAULT_MOTOR_VALUES],
    ["MG-LA1.QLD1.K1", DEFAULT_MOTOR_VALUES],
    ["MG-LA2.QLD2.K1", DEFAULT_MOTOR_VALUES],
    ["MG-LA3.QLF2.K1", DEFAULT_MOTOR_VALUES],
    ["MG-LA4.QLD3.K1", DEFAULT_MOTOR_VALUES],
]

ALL_MOTORS = HORIZONTAL_CORRECTORS + VERTICAL_CORRECTORS + QUADS

# METERS
DEFAULT_MONITOR_LIMITS = [-0.01, 0.01]

HORIZONTAL_MONITORS = [
    ["BI-LA1.PK3.Cx", DEFAULT_MONITOR_LIMITS],
    ["BI-LA2.PK4.Cx", DEFAULT_MONITOR_LIMITS],
    ["BI-LA3.PK5.Cx", DEFAULT_MONITOR_LIMITS],
    ["BI-LA4.PK6.Cx", DEFAULT_MONITOR_LIMITS],
]                       

VERTICAL_MONITORS = [
    ["BI-LA1.PK3.Cy", DEFAULT_MONITOR_LIMITS],
    ["BI-LA2.PK4.Cy", DEFAULT_MONITOR_LIMITS],
    ["BI-LA3.PK5.Cy", DEFAULT_MONITOR_LIMITS],
    ["BI-LA4.PK6.Cy", DEFAULT_MONITOR_LIMITS],   
]

ALL_MONITORS = HORIZONTAL_MONITORS + VERTICAL_MONITORS
