import sys

sys.path.append("../../")

from .base import *

from scaut.elegant import eleget, eleput

# GENERAL
NOISE_LEVEL = 0

VERIFY_MOTOR = False

DELAY = 0

TOLERANCE = 0.1

MAX_TRIES = 3

SAMPLE_SIZE = 5

SAVE_SCAN = True

DIRNAME_DATA = "data/dev"

SAVE_ORIGINAL_MOTOR_VALUES = False

PARALLEL = False

REPEAT = 1

GET_FUNC = eleget

PUT_FUNC = eleput

STRICT_CHECK = False

# ERRORS
ELEMENT_X_POSITION_ERROR = milli

ELEMENT_Y_POSITION_ERROR = milli

ELEMENT_Z_POSITION_ERROR = milli

ELEMENT_ROTATION_ERROR = milli

ELEMENT_FIELD_ERROR = milli

# MOTORS
DEFAULT_CORRECTOR_VALUES = [0] # A

DEFAULT_CORRECTOR_DELTA_KICK = 0.1

ALL_HORIZONTAL_CL_CORRECTORS = [  
    ["MG-LA1.CL1.HKICK", DEFAULT_CORRECTOR_VALUES],
    ["MG-LA1.CL2.HKICK", DEFAULT_CORRECTOR_VALUES],
    ["MG-LA2.CL3.HKICK", DEFAULT_CORRECTOR_VALUES],
    ["MG-LA3.CL4.HKICK", DEFAULT_CORRECTOR_VALUES],
    ["MG-LA4.CL5.HKICK", DEFAULT_CORRECTOR_VALUES],
    ["MG-LA5.CL6.HKICK", DEFAULT_CORRECTOR_VALUES],
]

ALL_VERTICAL_CL_CORRECTORS = [[name.replace("HKICK", "VKICK"), limits] for name, limits in ALL_HORIZONTAL_CL_CORRECTORS]

ALL_CORRECTORS = ALL_HORIZONTAL_CL_CORRECTORS + ALL_VERTICAL_CL_CORRECTORS

#MONITORS
DEFAULT_POSITION_MONITOR_LIMITS = [-0.01, 0.01] # m

ALL_HORIZONTAL_POSITION_LA_MONITORS = [
    ["BI-LA1.PK3.Cx", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-LA2.PK4.Cx", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-LA3.PK5.Cx", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-LA4.PK6.Cx", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-LA5.PK7.Cx", DEFAULT_POSITION_MONITOR_LIMITS], 
]

ALL_VERTICAL_POSITION_LA_MONITORS = [[name.replace("Cx", "Cy"), limits] for name, limits in ALL_HORIZONTAL_POSITION_LA_MONITORS]

ALL_HORIZONTAL_POSITION_MONITORS = ALL_HORIZONTAL_POSITION_LA_MONITORS

ALL_VERTICAL_POSITION_MONITORS = ALL_VERTICAL_POSITION_LA_MONITORS

ALL_POSITION_MONITORS = ALL_HORIZONTAL_POSITION_MONITORS + ALL_VERTICAL_POSITION_MONITORS
