from .base import *

from epics import caget, caput

# EPIC
try:
    caget("")
except Exception:
    ...
    
# GENERAL
NOISE_LEVEL = 0

VERIFY_MOTOR = False

DELAY = 0.5

TOLERANCE = 0.1

MAX_TRIES = 3

SAMPLE_SIZE = 1

SAVE_SCAN = True

DIRNAME_DATA = "data/prod"

SAVE_ORIGINAL_MOTOR_VALUES = False

PARALLEL = True

REPEAT = 1

GET_FUNC = caget

PUT_FUNC = caput

STRICT_CHECK = False

# MOTORS
DEFAULT_CORRECTOR_VALUES = [0] # A

DEFAULT_CORRECTOR_DELTA_KICK = 0.1

ALL_HORIZONTAL_CK_CORRECTORS = [  
    ["MG-LG:CKX1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LG:CKX2-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LG:CKX3-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LG:CKX4-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LG:CKX5-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LG:CKX6-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LG:CKX7-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LG:CKX8-I:Set", DEFAULT_CORRECTOR_VALUES],
]

ALL_VERTICAL_CK_CORRECTORS = [[name.replace("CKX", "CKY"), limits] for name, limits in ALL_HORIZONTAL_CK_CORRECTORS]

ALL_HORIZONTAL_CL_CORRECTORS = [  
    ["MG-LA1:CLX1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LA1:CLX2-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LA2:CLX3-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LA3:CLX4-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LA4:CLX5-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LA5:CLX6-I:Set", DEFAULT_CORRECTOR_VALUES],
]

ALL_VERTICAL_CL_CORRECTORS = [[name.replace("CLX", "CLY"), limits] for name, limits in ALL_HORIZONTAL_CL_CORRECTORS]

ALL_HORIZONTAL_TB_CORRECTORS = [  
    ["MG-TB1:CXW1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-TB2:CXW2-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-TB2:CXW3-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-TB2:CXW4-I:Set", DEFAULT_CORRECTOR_VALUES],
]

ALL_VERTICAL_TB_CORRECTORS = [  
    ["MG-TB1:CY1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-TB1:CY2-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-TB2:CY3-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-TB2:CY4-I:Set", DEFAULT_CORRECTOR_VALUES],
]

ALL_HORIZONTAL_BR_CORRECTORS = [
    ["MG-BCS:CXW1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BCS:CXW2-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA3:CX1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA3:CX2-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA3:CX3-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BES:CXW1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BES:CXW2-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA2:CX1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA2:CX2-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA2:CX3-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BDS:CXW1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BDS:CXW2-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA1:CX1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA1:CX2-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA1:CX3-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BIS:CXW1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BIS:CXW2-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA4:CX1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA4:CX2-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA4:CX3-I:Set", DEFAULT_CORRECTOR_VALUES],
]

ALL_VERTICAL_BR_CORRECTORS = [
    ["MG-BA3:CY1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA3:CY2-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA3:CY3-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA3:CY4-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA2:CY1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA2:CY2-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA2:CY3-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA2:CY4-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA1:CY1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA1:CY2-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA1:CY3-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA1:CY4-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA4:CY1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA4:CY2-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA4:CY3-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BA4:CY4-I:Set", DEFAULT_CORRECTOR_VALUES],
]

ALL_CORRECTORS = ALL_HORIZONTAL_CK_CORRECTORS + ALL_HORIZONTAL_CL_CORRECTORS + ALL_VERTICAL_CK_CORRECTORS+ ALL_VERTICAL_CL_CORRECTORS + ALL_HORIZONTAL_TB_CORRECTORS + ALL_VERTICAL_TB_CORRECTORS + ALL_HORIZONTAL_BR_CORRECTORS + ALL_VERTICAL_BR_CORRECTORS

ALL_QUADS = [
    ["MG-LA1:QLF1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LA1:QLD1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LA2:QLD2-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LA3:QLF2-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LA4:QLD3-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LA5:QLF3-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LA5:QLD4-I:Set", DEFAULT_CORRECTOR_VALUES],
    
    ["MG-TB1:QBF1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-TB1:QBD1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-TB1:QBD2-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-TB1:QBF2-I:Set", DEFAULT_CORRECTOR_VALUES],
    
    ["MG-TB2:QBD3-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-TB2:QBF3-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-TB2:QBD4-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-TB2:QBF4-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-TB2:QBD5-I:Set", DEFAULT_CORRECTOR_VALUES],

    ["MG-BR:QBF-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BR:QBD-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BR:QBG-I:Set", DEFAULT_CORRECTOR_VALUES],
]

ALL_SOLS = [
    ["MG-LG:SOLM-I:Set", DEFAULT_CORRECTOR_VALUES],
    
    ["MG-LG:SOLW1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LG:SOLW2-I:Set", DEFAULT_CORRECTOR_VALUES],
    
    ["MG-LG:SOL1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LG:SOL2-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LG:SOL3-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LG:SOL4-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-LG:SOL5-I:Set", DEFAULT_CORRECTOR_VALUES],    
]

ALL_BMS = [
    ["MG-TB1:BM1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-TB1:BM2-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-TB2:BM3-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-TB2:BM4-I:Set", DEFAULT_CORRECTOR_VALUES],

    ["MG-BR:BF-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BR:BD1-I:Set", DEFAULT_CORRECTOR_VALUES],
    ["MG-BR:BD2-I:Set", DEFAULT_CORRECTOR_VALUES],
]


#MONITORS
DEFAULT_POSITION_MONITOR_LIMITS = [-10, 10] # mm

DEFAULT_CURRENT_MONITOR_LIMITS = [0.01, 0.5] # mA

ALL_HORIZONTAL_POSITION_LG_MONITORS = [
    ["BI-LG:PK1-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-LG:PK2-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],  
]

ALL_HORIZONTAL_POSITION_LA_MONITORS = [
    ["BI-LA1:PK3-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-LA2:PK4-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-LA3:PK5-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-LA4:PK6-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-LA5:PK7-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS], 
]

ALL_HORIZONTAL_POSITION_TB_MONITORS = [
    ["BI-TB1:PK1-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-TB1:PK2-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-TB1:PK3-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-TB1:PK4-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-TB2:PK5-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-TB2:PK6-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-TB2:PK7-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-TB2:PK8-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
]

ALL_HORIZONTAL_POSITION_BA_MONITORS = [
    ["BI-BIS:PK2-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    
    ["BI-BA1:PK1-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA1:PK2-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA1:PK3-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA1:PK4-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA1:PK5-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA1:PK6-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA1:PK7-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    
    ["BI-BDS:PK1-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BDS:PK2-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    
    ["BI-BA2:PK1-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA2:PK2-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA2:PK3-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA2:PK4-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA2:PK5-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA2:PK6-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA2:PK7-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    
    ["BI-BES:PK1-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BES:PK2-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    
    ["BI-BA3:PK1-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA3:PK2-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA3:PK3-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA3:PK4-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA3:PK5-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA3:PK6-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA3:PK7-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    
    ["BI-BCS:PK1-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BCS:PK3-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    
    ["BI-BA4:PK1-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA4:PK2-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA4:PK3-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA4:PK4-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA4:PK5-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA4:PK6-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    ["BI-BA4:PK7-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
    
    ["BI-BIS:PK1-fastAvX:Mea", DEFAULT_POSITION_MONITOR_LIMITS],
]

ALL_VERTICAL_POSITION_LG_MONITORS = [[name.replace("AvX", "AvY"), limits] for name, limits in ALL_HORIZONTAL_POSITION_LG_MONITORS]

ALL_VERTICAL_POSITION_LA_MONITORS = [[name.replace("AvX", "AvY"), limits] for name, limits in ALL_HORIZONTAL_POSITION_LA_MONITORS]

ALL_VERTICAL_POSITION_TB_MONITORS = [[name.replace("AvX", "AvY"), limits] for name, limits in ALL_HORIZONTAL_POSITION_TB_MONITORS]

ALL_VERTICAL_POSITION_BA_MONITORS = [[name.replace("AvX", "AvY"), limits] for name, limits in ALL_HORIZONTAL_POSITION_BA_MONITORS]

ALL_HORIZONTAL_POSITION_MONITORS = ALL_HORIZONTAL_POSITION_LG_MONITORS + ALL_HORIZONTAL_POSITION_LA_MONITORS + ALL_HORIZONTAL_POSITION_TB_MONITORS + ALL_HORIZONTAL_POSITION_BA_MONITORS

ALL_VERTICAL_POSITION_MONITORS = ALL_VERTICAL_POSITION_LG_MONITORS + ALL_VERTICAL_POSITION_LA_MONITORS + ALL_VERTICAL_POSITION_TB_MONITORS + ALL_VERTICAL_POSITION_BA_MONITORS

ALL_POSITION_MONITORS = ALL_HORIZONTAL_POSITION_MONITORS + ALL_VERTICAL_POSITION_MONITORS

ALL_CURRENT_MONITORS = [[name.replace("AvX", "AvI"), DEFAULT_CURRENT_MONITOR_LIMITS] for name, _ in ALL_HORIZONTAL_POSITION_MONITORS]

ALL_CHARGE_MONITORS = [[name.replace("AvX", "AvC"), DEFAULT_CURRENT_MONITOR_LIMITS] for name, _ in ALL_HORIZONTAL_POSITION_MONITORS]
