from .base import *

from epics import caget, caput

# GENERAL
NOISE_LEVEL = 0

VERIFY_MOTOR = True

DELAY = milli

TOLERANCE = 0.1

MAX_TRIES = 3

SAMPLE_SIZE = 10

SAVE_SCAN = True

DIRNAME_DATA = "data/prod"

SAVE_ORIGINAL_MOTOR_VALUES = True

PARALLEL = False

GET_FUNC = caget

PUT_FUNC = caput

# MOTORS
DEFAULT_MOTOR_VALUES = [0]

DEFAULT_DELTA_KICK = 0.1

HORIZONTAL_CORRECTORS = [  
    ["MG-LA1:CLX1-I:Set", DEFAULT_MOTOR_VALUES],
    ["MG-LA1:CLX2-I:Set", DEFAULT_MOTOR_VALUES],
    ["MG-LA2:CLX3-I:Set", DEFAULT_MOTOR_VALUES],
    ["MG-LA3:CLX4-I:Set", DEFAULT_MOTOR_VALUES],
    ["MG-LA4:CLX5-I:Set", DEFAULT_MOTOR_VALUES],
    ["MG-LA5:CLX6-I:Set", DEFAULT_MOTOR_VALUES],
]

VERTICAL_CORRECTORS = [  
    ["MG-LA1:CLY1-I:Set", DEFAULT_MOTOR_VALUES],
    ["MG-LA1:CLY2-I:Set", DEFAULT_MOTOR_VALUES],
    ["MG-LA2:CLY3-I:Set", DEFAULT_MOTOR_VALUES],
    ["MG-LA3:CLY4-I:Set", DEFAULT_MOTOR_VALUES],
    ["MG-LA4:CLY5-I:Set", DEFAULT_MOTOR_VALUES],
    ["MG-LA5:CLY6-I:Set", DEFAULT_MOTOR_VALUES],     
]

DEFAULT_MOTOR_VALUES = [0]

QUADS = [
    ["MG-LA1:QLF1-I:Set", DEFAULT_MOTOR_VALUES],
    ["MG-LA1:QLD1-I:Set", DEFAULT_MOTOR_VALUES],
    ["MG-LA2:QLD2-I:Set", DEFAULT_MOTOR_VALUES],
    ["MG-LA3:QLF2-I:Set", DEFAULT_MOTOR_VALUES],
    ["MG-LA4:QLD3-I:Set", DEFAULT_MOTOR_VALUES],
]

ALL_MOTORS = HORIZONTAL_CORRECTORS + VERTICAL_CORRECTORS + QUADS

#MONITORS
DEFAULT_MONITOR_LIMITS = [-10, 10]

HORIZONTAL_MONITORS = [
    ["BI-LA1:PK3-fastAvX:Mea", DEFAULT_MONITOR_LIMITS],
    ["BI-LA2:PK4-fastAvX:Mea", DEFAULT_MONITOR_LIMITS],
    ["BI-LA3:PK5-fastAvX:Mea", DEFAULT_MONITOR_LIMITS],
    ["BI-LA4:PK6-fastAvX:Mea", DEFAULT_MONITOR_LIMITS],
]                       

VERTICAL_MONITORS = [
    ["BI-LA1:PK3-fastAvY:Mea", DEFAULT_MONITOR_LIMITS],
    ["BI-LA2:PK4-fastAvY:Mea", DEFAULT_MONITOR_LIMITS],
    ["BI-LA3:PK5-fastAvY:Mea", DEFAULT_MONITOR_LIMITS],
    ["BI-LA4:PK6-fastAvY:Mea", DEFAULT_MONITOR_LIMITS],    
]

ALL_MONITORS = HORIZONTAL_MONITORS + VERTICAL_MONITORS
